services:
  dljupyter:
    build: .
    restart: always
    ports:
      - "80:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
